---
version: '2.4'
services:
  monitor:
    build:
      context: ..
      dockerfile: monitor/Dockerfile
    ports:
    - "${MONITOR_PORT}:${MONITOR_PORT}"
    env_file: ./.env
    environment: 
      - NODE_ENV=production
    volumes:
      - ./responses:/mono/monitor/responses
    restart: unless-stopped
    entrypoint: "yarn start"
